### ISSUE TITLE
AttributeError: 'module' object has no attribute 'open'

### ISSUE THREAD

**Issue by yhoogstrate** [ssokolow/unball#1]
When I want to install, I end up with the following error:

~/Desktop/unball-master$ sudo python setup.py build
running build
running build_py
running build_scripts
running build_manpage
Traceback (most recent call last):
  File "setup.py", line 70, in <module>
    'parser': 'unball.main:get_opt_parser',
  File "/usr/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 971, in run_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "/home/youri/Desktop/unball-master/build_manpage.py", line 50, in finalize_options
    mod = **import**(mod_name, fromlist=fromlist)
  File "/home/youri/Desktop/unball-master/unball/main.py", line 51, in <module>
    from .mimetypes import pathToMimetype
  File "/home/youri/Desktop/unball-master/unball/mimetypes.py", line 34, in <module>
    mime_checker = magic.open(magic.MAGIC_MIME)
AttributeError: 'module' object has no attribute 'open'

Am I missing some dependencies?

**Comment by ssokolow** [comment]
Not quite. You've tripped over an edge case I didn't think could happen. (You have a "magic" module, so the fallback doesn't kick in, but it's not the right "magic" module, so the code fails.)

What platform are you on? I'd like to track down this "other 'magic' module" and satisfy my curiosity about it before I write a fix.
